### ISSUE TITLE
Security: That's not your real password, right?

### ISSUE THREAD

**Issue by Kaamkiya** [rdnt/myst#258]
The preview image shows your Github account. If that's your real password, CHANGE IT.

I doubt it is, but just in case.

**Comment by rdnt** [comment]
@Kaamkiya no worries, it was just a randomly generated password I created on the spot. I reckon, in some other screenshot, I modified the description to say "not my real password of course", but it didn't make it to the README. 😅

Thanks a lot for the heads-up however, I appreciate it! 🙏

**Comment by Kaamkiya** [comment]
Okay, great. Just making sure :)
